# Generated by Django 4.1 on 2022-08-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Bad'), ('O', 'OK'), ('G', 'Great')], default='G', max_length=1)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bond')),
            ],
        ),
    ]
