# Generated by Django 4.1 on 2022-08-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gadjet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='gadjets',
            field=models.ManyToManyField(to='main_app.gadjet'),
        ),
    ]
